#!/bin/bash
mkdir -p media/performance

pushd media/performance
curl -O -s https://s3.cycore.io/kineticlight/performance/0george.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/0george.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/0george.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/1abump.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/1abump.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/1abump.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/1adavid.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/1adavid.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/1adavid.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/1adylan.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/1adylan.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/1adylan.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/1ageorge.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/1ageorge.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/1ageorge.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/1aheader.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/1aheader.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/1aheader.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/1bbump.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/1bbump.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/1bbump.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/1bdavid.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/1bdavid.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/1bdavid.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/1bdylan.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/1bdylan.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/1bdylan.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/1bgeorge.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/1bgeorge.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/1bgeorge.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/1bheader.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/1bheader.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/1bheader.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/1bump.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/1bump.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/1bump.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/1david.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/1david.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/1david.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/1dylan.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/1dylan.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/1dylan.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/1george.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/1george.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/1george.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/1header.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/1header.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/1header.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/2abump.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/2abump.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/2abump.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/2adavid.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/2adavid.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/2adavid.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/2adylan.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/2adylan.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/2adylan.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/2ageorge.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/2ageorge.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/2ageorge.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/2aheader.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/2aheader.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/2aheader.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/2bbump.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/2bbump.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/2bbump.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/2bdavid.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/2bdavid.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/2bdavid.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/2bdylan.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/2bdylan.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/2bdylan.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/2bgeorge.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/2bgeorge.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/2bgeorge.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/2bheader.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/2bheader.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/2bheader.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/2bump.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/2bump.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/2bump.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/2david.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/2david.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/2david.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/2dylan.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/2dylan.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/2dylan.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/2george.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/2george.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/2george.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/2header.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/2header.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/2header.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/3bump.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/3bump.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/3bump.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/3david.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/3david.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/3david.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/3dylan.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/3dylan.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/3dylan.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/3george.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/3george.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/3george.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/3header.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/3header.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/3header.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/4bump.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/4bump.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/4bump.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/4david.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/4david.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/4david.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/4dylan.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/4dylan.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/4dylan.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/4george.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/4george.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/4george.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/4header.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/4header.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/4header.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/5bump.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/5bump.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/5bump.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/5david.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/5david.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/5david.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/5dylan.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/5dylan.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/5dylan.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/5george.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/5george.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/5george.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/5header.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/5header.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/5header.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/6bump.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/6bump.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/6bump.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/6david.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/6david.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/6david.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/6dylan.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/6dylan.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/6dylan.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/6george.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/6george.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/6george.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/6header.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/6header.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/6header.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/7bump.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/7bump.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/7bump.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/7david.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/7david.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/7david.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/7dylan.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/7dylan.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/7dylan.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/7george.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/7george.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/7george.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/7header.m4a
curl -O -s https://s3.cycore.io/kineticlight/performance/7header.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/7header.webm
curl -O -s https://s3.cycore.io/kineticlight/performance/headers.mp3
curl -O -s https://s3.cycore.io/kineticlight/performance/headers.webm
